In [ ]:
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.tree import export_graphviz
import graphviz

dataset = pd.read_csv('zoo_data.csv')

x_train = dataset.iloc[:80,:-1]
x_test = dataset.iloc[80:,:-1]
y_train = dataset.iloc[:80,-1]
y_test = dataset.iloc[80:,-1]

tree1 = DecisionTreeClassifier(criterion = 'entropy').fit(x_train,y_train)
export_graphviz(tree1, out_file="mytree.dot")
with open("mytree.dot") as f:
    dot_graph = f.read()
graphviz.Source(dot_graph)


prediction = tree1.predict(x_test)
cm = confusion_matrix(y_test, prediction)
print(cm)
FP = cm.sum(axis=0) - np.diag(cm)
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)
print('False Positives\n {}'.format(FP))
print('False Negatives\n {}'.format(FN))
print('True Positives\n {}'.format(TP))
print('True Negatives\n {}'.format(TN))
TPR = TP/(TP+FN)
print('Sensitivity \n {}'.format(TPR))
TNR = TN/(TN+FP)
print('Specificity \n {}'.format(TNR))
Precision = TP/(TP+FP)
print('Precision \n {}'.format(Precision))
Recall = TP/(TP+FN)
print('Recall \n {}'.format(Recall))
Acc = (TP+TN)/(TP+TN+FP+FN)
print('Áccuracy \n{}'.format(Acc))
Fscore = 2*((Precision*Recall)/(Precision+Recall))
print('FScore \n{}'.format(Fscore))

[[5 0 0 0 0 0 0]
 [0 4 0 0 0 0 0]
 [0 0 0 0 1 0 1]
 [0 0 0 3 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 2 0]
 [0 0 0 0 0 2 1]]
False Positives
 [0 0 0 0 1 2 1]
False Negatives
 [0 0 2 0 0 0 2]
True Positives
 [5 4 0 3 1 2 1]
True Negatives
 [15 16 18 17 18 16 16]
Sensitivity 
 [1.         1.         0.         1.         1.         1.
 0.33333333]
Specificity 
 [1.         1.         1.         1.         0.94736842 0.88888889
 0.94117647]
Precision 
 [1.  1.  nan 1.  0.5 0.5 0.5]
Recall 
 [1.         1.         0.         1.         1.         1.
 0.33333333]
Áccuracy 
[1.   1.   0.9  1.   0.95 0.9  0.85]
FScore 
[1.         1.                nan 1.         0.66666667 0.66666667
 0.4       ]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:60: RuntimeWarning: invalid value encountered in true_divide
